### PR TITLE
added merge sort algorithm in python

### PR DESCRIPTION
**Pull request by TishaJhabak1014**
Added one of the most common algorithms under `divide and conquer` , i.e `merge sort` implemented in python.

### CODE REVIEW

**Comment by TishaJhabak1014** [comment]
@kavyanshpandey Added an algorithm in .py file. Plz merge if it helps. Plz kindly do add the labels `hacktoberfest` and `hacktoberfest-accepted`. Thank you for this repository.

**Comment by TishaJhabak1014** [comment]
@kavyanshpandey Please add the labels ; )

**Comment by kavyanshpandey** [comment]
That's is not mandatory...
Merged or hacktoberfest-accepted label both with counts towards completion.

**Comment by TishaJhabak1014** [comment]
> That's is not mandatory... Merged or hacktoberfest-accepted label both with counts towards completion.

Okay, Thank you. Lokking forward to contribute to other repositories.

**Pull request merged**
