### PR TITLE
Created tanya.md file

### PR DESCRIPTION
**Pull request by TD-17**

### CODE REVIEW

**Comment by TD-17** [comment]
Hi @kavyanshpandey ! My hacktoberfest dashboard says that pull request not yet accepted
Screenshot (70)
.

**Comment by kavyanshpandey** [comment]
Actually sometimes it will take much time to reflect changes on dashboards.

No worry!! It will reflect few minutes

**Comment by TD-17** [comment]
> Actually sometimes it will take much time to reflect changes on dashboards.
> 
> No worry!! It will reflect in few minutes

OKay! Thanks

**Comment by TD-17** [comment]
Screenshot (74)

It says excluded project!

**Comment by kavyanshpandey** [comment]
Hey, yes this project has been excluded by hacktoberfest on yesterday night..

You can make PRs on other pinned repositories, I will merge it🤟🤟

**Comment by kavyanshpandey** [comment]
And it will count towards completion

**Pull request merged**
