### PR TITLE
new .md file added

### PR DESCRIPTION
**Pull request by thedevshubham**
Shubham Bhatt md file added to the hacktoberfest 2021 contribution

### CODE REVIEW

**Comment by thedevshubham** [comment]
@kavyanshpandey this is showing excluded project in my hacktoberfest profile

**Comment by kavyanshpandey** [comment]
Can you please share the screenshot?

**Comment by thedevshubham** [comment]
hck1

**Comment by thedevshubham** [comment]
@kavyanshpandey please check the screen shot

**Comment by kavyanshpandey** [comment]
Yes I also found that…No worry you can raise Pr on other pin repository,
I’ll provide label name as accepted👍🏻

**Pull request merged**
