### PR TITLE
Armstrong Number

### PR DESCRIPTION
**Pull request by codedoc7**
Armstrong Number program in C++

### CODE REVIEW

**Comment by sonikasahoo** [comment]
Hello @kavyanshpandey , this is my 1st contribution to open source projects. Can you please assign me this ?
I want to make this using python.

**Comment by kavyanshpandey** [comment]
Hii...actually assignee is the different things on Github.. 

You can fork this repositories,
Make changes and push the code 


I'll merge it

**Comment by sonikasahoo** [comment]
Okk @kavyanshpandey  Thank you sir

**Comment by kavyanshpandey** [comment]
I suggest you to make changes on the pinned repos..

This repo is not the part of hacktoberfest project..

You can make PR on covid 19- tracker, Sneha Cafe etc repos that are available in my repos section..

Make any change what ever you want...I'll provide label as hacktoberfest accepted...and it will count towards completion..

**Comment by sonikasahoo** [comment]
Okk

**Comment by codedoc7** [comment]
Hi @sonikasahoo  if you want to contribute, go ahead just let me close this PR and make new PR from yours side 
Okay👍🏽

**Pull request closed without merging**
